   <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
     <div class="container">
       <a class="navbar-brand" href="index.php"><?= nama; ?></a>
       <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
         data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
         aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarResponsive">
         <ul class="navbar-nav ml-auto">

           <li class="nav-item">
             <a class="nav-link" href="tayang.php">Jadwal Tayang</a>
           </li>

           <li class="nav-item dropdown">
             <?php if ($_SESSION['username']) {
                $uss = $_SESSION['username'];
                $saldosaya = $conn->query("SELECT saldo_konsumen FROM konsumen WHERE username_konsumen = '$uss' OR email_konsumen = '$uss'");
                $saldoo = $saldosaya->fetch_assoc();
                ?>
             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
               Akun Saya
             </a>

             <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
               <a class="dropdown-item"
                 <?php if (isset($_SESSION['admin']) or isset($_SESSION['kasir'])) { ?>href="home"
                 <?php } else { ?>href="akunsaya.php" <?php } ?>>Dashboard</a>
               <?php if (isset($_SESSION['admin']) or isset($_SESSION['kasir'])) { ?> <?php } else { ?><a
                 class="dropdown-item">Saldo Saya : <?php echo $saldoo['saldo_konsumen']; ?></a><?php } ?>
               <a class="dropdown-item" href="logout.php">Logout</a>
             </div>
             <?php } else { ?>

             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
               Masuk/Daftar
             </a>
             <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
               <a class="dropdown-item" href="login.php">Masuk</a>
               <a class="dropdown-item" href="daftar.php">Daftar</a>
             </div>
             <?php } ?>
           </li>

         </ul>
       </div>
     </div>
   </nav>